### ISSUE TITLE
Francium.tech shows as down

### ISSUE THREAD

**Issue by bragboy** [itsgg/zsh-isup#1]
Although up it shows as down

<img width="475" alt="image" src="https://github.com/user-attachments/assets/9deb34a3-555b-449d-b400-e81b0ab1a45b">
<img width="363" alt="image" src="https://github.com/user-attachments/assets/44b5a711-3e9d-4a9a-9f83-88a51510d6a3">

**Comment by itsgg** [comment]
![image](https://github.com/user-attachments/assets/a9f718d5-f135-4bd7-9740-90d87dea1fc6)
 @bragboy
